name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: "Linux python"
            os: ubuntu-20.04

          - name: "macOS"
            os: macos-latest
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: update pip
      run: |
        python3 -m pip install --upgrade pip
    - name: depend
      run: |
        pip install -r requirements.txt
    - name: run test
      run: |
        python3 test/test_bilibili.py
