name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: update pip
      run: |
        /opt/hostedtoolcache/Python/3.6.13/x64/bin/python -m pip install --upgrade pip
    - name: depend
      run: |
        pip list | grep urllib
        $conda/bin/conda install urllib3
    - name: run test
      run: |
        python test/test_bilibili.py
